[package]
name = "wow_ls"
version = "0.1.0"
repository = "https://github.com/plusmouse/wow_ls" 
edition = "2024"
licence = "GPLv3"

[dependencies]
lsp-server = "=0.7.8"
lsp-types = "0.97.0"
rowan = "0.16.1"
serde = "1.0.219"
serde_json = "1.0.140"
