[package]
name = "wow_ls"
version = "0.1.0"
repository = "https://github.com/plusmouse/wow_ls" 
edition = "2024"
licence = "GPLv3"

[dependencies]
codespan-reporting = "0.12.0"
full_moon = "2.0.0"
lsp-server = "=0.7.8"
lsp-types = "0.97.0"
serde = "1.0.219"
serde_json = "1.0.140"
